- name: install redis dependencies
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ redis_required_packages }}"
  tags:
    - redis

- name: download latest stable redis
  get_url:
    url: http://download.redis.io/redis-stable.tar.gz
    dest: /tmp/redis-stable.tar.gz
  tags:
    - redis

- name: untar redis
  unarchive:
    src: /tmp/redis-stable.tar.gz
    dest: /tmp
    remote_src: yes
  tags:
    - redis

- name: build redis
  command: make -C /tmp/redis-stable
  tags:
    - redis

- name: create redis group
  become: yes
  become_user: root
  group:
    name: redis
    state: present
    system: yes
  tags:
    - redis

- name: create redis user
  become: yes
  become_user: root
  user:
    name: redis
    group: redis
    createhome: no
    shell: /bin/false
    system: yes
    state: present
  tags:
    - redis

- name: make sure that /etc/redis exists
  become: yes
  become_user: root
  file:
    path: /etc/redis
    state: directory
    mode: 0755
  tags:
    - redis

- name: make sure that /var/db/redis exists
  become: yes
  become_user: root
  file:
    path: /var/db/redis
    state: directory
    mode: 0755
    group: redis
    owner: redis
  tags:
    - redis

- name: make sure redis.log file exists
  become: yes
  become_user: root
  copy:
    src: templates/redis.log
    dest: /var/log/redis.log
    owner: redis
    group: redis
    mode: 0644
  tags:
    - redis

- name: copy upstart file
  become: yes
  become_user: root
  copy:
    src: templates/upstart.conf
    dest: /etc/init/redis.conf
  tags:
    - redis

- name: copy redis.conf file
  become: yes
  become_user: root
  copy:
    src: templates/redis.conf
    dest: /etc/redis/redis.conf
    group: redis
    owner: redis
  tags:
    - redis

- name: copy custom template
  become: yes
  become_user: root
  template:
    src: templates/redis.local.conf.j2
    dest: /etc/redis/redis.local.conf
    group: redis
    owner: redis
  tags:
    - redis

- name: copy redis-local script
  become: yes
  become_user: root
  template:
    src: templates/redis-local.j2
    dest: /usr/local/bin/redis-local
    mode: 0755
  tags:
    - redis

- name: install redis binaries
  become: yes
  become_user: root
  file:
    src: "/tmp/redis-stable/src/{{ item }}"
    dest: /usr/local/bin
  with_items: 
    - redis-server
    - redis-cli
    - redis-check-aof
  tags:
    - redis

- name: clean up build files
  become: yes
  become_user: root
  file:
    path: '/tmp/{{ item }}'
    state: absent
  with_items:
    - redis-stable
    - redis-stable.tar.gz
  tags:
    - redis
