# Shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.zsh

# Add each folder to fpath
for folder ($ZSH/*) if [ -d $folder ]; then fpath=($folder $fpath); fi;

# Setup zsh scripts
typeset -U config_files
config_files=($ZSH/**/*.zsh)

# Load path files
for file in ${(M)config_files:#*/path.zsh}; do
  source $file
done

# Load env files
for file in ${(M)config_files:#*/env.zsh}; do
  source $file
done

# Load evertyhing else
for file in ${${config_files:#*/path.zsh}:#*/env.zsh}; do
  source $file
done

unset config_files

# Local configs
[[ -f $HOME/.zshrc.local ]] && source $HOME/.zshrc.local
