neovim_repo: ppa:neovim-ppa/stable
neovim_package: neovim
neovim_config_dir: "{{ home_dir }}/.config/nvim"

vim_plugged_dir: "{{ home_dir }}/.config/nvim/plugged"
vim_plug_repo: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
