- name: copy .gitconfig
  template:
    src: "{{ role_path }}/templates/gitconfig.j2"
    dest: "{{ home_dir }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
    - git

- name: copy .gitignore
  copy:
    src: "{{ role_path }}/files/gitignore"
    dest: "{{ home_dir }}/.gitignore"
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
    - git
