- name: update apt
  become: yes
  become_user: root
  apt:
    update_cache: yes
  tags:
    - pre_build

- name: upgrade packages
  become: yes
  become_user: root
  apt:
    upgrade: dist
  tags:
    - pre_build

- name: install general dependencies
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - "{{ general_required_packages }}"
  tags:
    - pre_build
